image: microsoft/dotnet:2.1-sdk


stages:
  - build
  - test
  - deploy


job_build:
  stage: build
  before_script:
    - echo building...
    - dotnet --info
    - dotnet restore
  script:
    - dotnet build 

job_release:
  stage: deploy
  script:
    - dotnet publish -c Release -o ../publish
    - docker build -t  blog-netcore-api  .
    # 删除已经在运行的容器
    - if [ $(docker ps -aq --filter name= cicd-demo) ]; then docker rm -f cicd-demo;fi
    # 通过镜像启动容器，并把本机8000端口映射到容器8000端口
    - docker run -d -p 8080:80 --name blog    blog-netcore-api
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}_pipeline${CI_PIPELINE_ID}_job${CI_JOB_ID}"
    when: on_success
    expire_in: 1 mos and 2 weeks
    paths: 
      - publish/
  tags:
     - gitlabrunner
  only:
    - master
