image: microsoft/dotnet:2.1-sdk

variables:
  IMAGE_TAG: ${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
  Solution: ./src/Blog.Api/Blog.Api.csproj

stages:
    - test
    - build
    - deploy

job_build:
    stage: test
    before_script:
        - echo building...
        - dotnet --info
        - dotnet restore $Solution
    script:
        - dotnet build $Solution

.unit_test:
     stage: test
     before_script:
        - dotnet restore $Solution
     script: 
        - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../coverage
     artifacts:
        when: on_success
        name: "code-coverage-${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}_pipeline${CI_PIPELINE_ID}_job${CI_JOB_ID}"
        expire_in: 1 mos and 2 weeks
        paths:
          - coverage/


    
publish_package:
    stage: test
    before_script:
        - dotnet --info
        - dotnet build $Solution
    script:
        - dotnet publish -c Release $Solution  -o ../../publish
    artifacts:
        name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}_pipeline${CI_PIPELINE_ID}_job${CI_JOB_ID}"
        when: on_success
        expire_in: 1 mos and 2 weeks
        paths: 
          - publish/
    only:
        - master   

job_build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker --version
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}
  script:
      - docker build --build-arg GIT_COMMIT=$CI_COMMIT_SHA -t ${CI_REGISTRY_IMAGE}:${IMAGE_TAG} .
      - docker images
      - docker push ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
  only:
      - master 
      - /^feature-.*$/
  allow_failure: false
 
deploy_gdev:
    stage: deploy
    variables:
        DOMAIN: 47.101.152.254:8080 
    before_script:
         - docker-compose ps
         - docker-compose stop web
         - docker-compose rm web -f 
    script:
         - docker-compose up -d  --build
    after_script:
         - docker image prune -f -a
    environment:
        name: gdev
        url: http://${DOMAIN}/swagger/
    when: on_success
    tags:
        - runner02
    only:
        - master   

