version: '3.5'
services:
  web:
    image: ${VPC_CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    ports:
       - 8081:80
    networks:
       - overlay
    privileged: true
    container_name: blog-api
    links:
       - db
       - redis
    depends_on:
       - db
       - redis
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    env_file:
       - web-variables.env
    volumes:
      - "/blog/api/appsettings.Production.json:/app/appsettings.Production.json"
      - "/blog/api/wwwroot:/app/wwwroot"
  
  db:
     image: mysql:5.7
     privileged: true
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     container_name: mysql
     env_file:
       - db-variables.env
     volumes:
       - "/blog/db/init:/docker-entrypoint-initdb.d/"
       - "/blog/db/data:/var/lib/mysql"
  redis: 
     image: redis
     restart: always
     privileged: true
     ports:
       - 6379:6379
     container_name: redis
     networks:
       - overlay
     volumes:
       - "/blog/redis/data:/data"
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx    
    restart: always
    container_name: nginx
    networks:
       - overlay
    ports:
       - 80:80
       - 8443:443
    links:
       - web
    volumes:
      - /blog/nginx-about/nginx.conf:/etc/nginx/conf.d/default.conf
      - /blog/nginx-about/cert:/etc/nginx/cert

  
networks:
  overlay:
  

