version: '3'
services:
  web:
    build: .
    ports:
       - 8080:80
    networks:
       - overlay
    container_name: blog-api
    volumes:
       - log-data:/app/log
    links:
       - db
    depends_on:
       - db
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    privileged: true

  db:
     image: mysql:5.7
     privileged: true
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     container_name: mysql
     command: --default_authentication_plugin=mysql_native_password   --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
       - MYSQL_ROOT_PASSWORD="123456"
       - MYSQL_DATABASE="blog"
       - MYSQL_USER="root"
       - MYSQL_PASSWORD="123456"
     volumes:
       - db-data:/var/lib/mysql
       - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    

volumes:
   log-data:
   db-data:

networks:
  overlay:
  

