version: '3'
services:
  web:
    image: ${VPC_CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    ports:
       - 8080:80
    networks:
       - overlay
    container_name: blog-api
    links:
       - db
       - redis
    depends_on:
       - db
       - redis
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
       - Version=${CI_COMMIT_SHA:0:8}
    privileged: true
  db:
     image: mysql:5.7
     privileged: true
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=123456
     volumes:
       - "./db/init:/docker-entrypoint-initdb.d/"
       - "./db/data:/var/lib/mysql"
  redis: 
     image: redis
     restart: always
     privileged: true
     ports:
       - 6379:6379
     container_name: redis
     networks:
       - overlay
     volumes:
       - "./redis/data:/data"
networks:
  overlay:
  

