version: '3'
services:
  web:
    images: ${VPC_CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    ports:
       - 8080:80
    networks:
       - overlay
    container_name: blog-api
    links:
       - db
       - redis
    depends_on:
       - db
       - redis
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    privileged: true
  db:
     image: mysql:5.7
     privileged: true
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=123456
     volumes:
       - "./init:/docker-entrypoint-initdb.d/"
  redis: 
     image: redis
     restart: always
     privileged: true
     ports:
       - 6379:6379
     container_name: redis
     networks:
       - overlay
networks:
  overlay:
  

