version: '3'
services:
  web:
    build: .
    ports:
       - 8080:80
    networks:
       - overlay
    container_name: blog-api
    links:
       - db
    depends_on:
       - db
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    privileged: true
  db:
     image: mysql:5.7
     privileged: true
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=123456
     volumes:
       - "./init:/docker-entrypoint-initdb.d/"

networks:
  overlay:
  

