version: '3'
services:
  web:
    build: .
    ports:
       - 8080:80
    networks:
       - overlay
    container_name: blog
    volumes:
       - app/log:/var/blog/blogapi/log
    depends_on:
       - db
  db:
     image: mysql:5.7
     restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     #container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD:"i<=2359loveN"
     volumes:
       - db-data:/var/lib/mysql
volumes:
   db-data:
   app/log:

networks:
  overlay:
  

