version: '3'
services:
  web:
    build: .
    ports:
       - 8080:80
    networks:
       - overlay
    #container_name: blog
    volumes:
       - log-data:/app/log
    links:
       - db
    depends_on:
       - db
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
  db:
     image: mysql:5.7
     #restart: always
     ports:
       - 3306:3306
     networks:
       - overlay
     command:"mysql -uroot -p123456 <db.sql"
     environment:
       - MYSQL_ROOT_PASSWORD="123456"
       - MYSQL_DATABASE="blog"
       - MYSQL_USER="root"
       - MYSQL_PASSWORD="123456"
     volumes:
       - db-data:/var/lib/mysql
volumes:
   log-data:
   db-data:

networks:
  overlay:
  

